---
# yaml-language-server: $schema=https://k8s-schemas.aresu.eu/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keda-add-ons-http
spec:
  chartRef:
    kind: OCIRepository
    name: keda-add-ons-http
  interval: 30m
  values:
    interceptor:
      tcpConnectTimeout: 5000ms # default: 500ms
      keepAlive: 10s # default: 1s
      responseHeaderTimeout: 5000ms # default: 500ms
