---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-backups
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cnpg-backups-secret
    template:
      engineVersion: v2
      data:
        ACCESS_KEY_ID: "{{ .ACCESS_KEY_ID }}"
        ACCESS_SECRET_KEY: "{{ .ACCESS_SECRET_KEY }}"
        REGION: "{{ .REGION }}"
  dataFrom:
    - extract:
        key: cnpg-backups
