---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/barmancloud.cnpg.io/objectstore_v1.json
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: cloudnative-pg-backups-store
spec:
  configuration:
    destinationPath: s3://postgres/
    endpointURL: http://garage-app.selfhosted.svc.cluster.local:3900
    s3Credentials:
      accessKeyId:
        name: cloudnative-pg-backups-secret
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: cloudnative-pg-backups-secret
        key: ACCESS_SECRET_KEY
      region:
        name: cloudnative-pg-backups-secret
        key: REGION
    wal:
      compression: zstd
    data:
      compression: gzip
  retentionPolicy: "30d"
