---
# yaml-language-server: $schema=https://k8s-schemas.aresu.eu/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname home-assistant-external
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 1h
  path: "./kubernetes/apps/home-automation/home-assistant/external"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: home-automation
  timeout: 5m
  wait: false
