[settings]
pipx_uvx = true

[env]
JUST_UNSTABLE = "1"
KUBECONFIG = '{{config_root}}/kubeconfig'
MINIJINJA_CONFIG_FILE = "{{config_root}}/.minijinja.toml"
TALOSCONFIG = '{{config_root}}/talosconfig'

[tools]
"aqua:astral-sh/uv" = ["latest"]
"aqua:casey/just" = "1.46.0"
"aqua:cloudflare/cloudflared" = "2025.11.1"
"aqua:FiloSottile/age" = "1.3.1"
"aqua:fluxcd/flux2" = "2.7.5"
"aqua:getsops/sops" = "3.11.0"
"aqua:go-task/task" = "3.46.4"
"aqua:google/yamlfmt" = ["latest"]
"aqua:helm/helm" = "4.1.0"
"aqua:helmfile/helmfile" = "1.2.3"
"aqua:jqlang/jq" = "1.8.1"
"aqua:kubernetes-sigs/kustomize" = "5.7.1"
"aqua:kubernetes/kubectl" = "1.33.3"
"aqua:mikefarah/yq" = "4.50.1"
"aqua:siderolabs/talos" = "1.12.0"
"aqua:yannh/kubeconform" = "0.7.0"
"pipx:flux-local" = ["latest"]
