---
# yaml-language-server: $schema=https://k8s-schemas.aresu.eu/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname smartctl-exporter
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: *appname
      namespace: observability
  interval: 1h
  path: "./kubernetes/apps/observability/smartctl-exporter/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: observability
  timeout: 5m
  wait: false
