---
# yaml-language-server: $schema=https://k8s-schemas.aresu.eu/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: homeassistant
  annotations:
    hajimari.io/enable: "true"
    hajimari.io/icon: "home-assistant"
  labels:
    name: homeassistant
spec:
  hostnames:
    - homeassistant.aresu.eu
  parentRefs:
    - name: envoy-external
      namespace: network
  rules:
    - backendRefs:
        - name: homeassistant
          port: 8123
