---
# yaml-language-server: $schema=https://k8s-schemas.aresu.eu/tuppr.home-operations.com/talosupgrade_v1alpha1.json
apiVersion: tuppr.home-operations.com/v1alpha1
kind: TalosUpgrade
metadata:
  name: talos
spec:
  talos:
    # renovate: datasource=docker depName=ghcr.io/siderolabs/installer
    version: v1.11.6
  policy:
    rebootMode: default
  # healthChecks: # Not really working, some stay True even if correctly synced
  #   - apiVersion: volsync.backube/v1alpha1
  #     kind: ReplicationSource
  #     expr: |-
  #       status.conditions.filter(c, c.type == "Synchronizing").all(c, c.status == "False")
