---
# yaml-language-server: $schema=https://k8s-schemas.aresu.eu/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: homeassistant-paola
  annotations:
    hajimari.io/enable: "true"
    hajimari.io/icon: "home-assistant"
  labels:
    name: homeassistant-paola
spec:
  hostnames:
    - homeassistant-paola.aresu.eu
  parentRefs:
    - name: envoy-external
      namespace: network
  rules:
    - backendRefs:
        - group: gateway.envoyproxy.io
          kind: Backend
          name: home-assistant-paola
      matches:
        - path:
            type: PathPrefix
            value: /
