---
# yaml-language-server: $schema=https://k8s-schemas.aresu.eu/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname lidarr
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  components:
    - ../../../../components/volsync
    - ../../../../components/keda/nas-nfs-scaler
  dependsOn:
    - name: longhorn-volumesnapshotclass
      namespace: longhorn
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: *appname
      namespace: downloads
  interval: 1h
  path: "./kubernetes/apps/downloads/lidarr/app"
  postBuild:
    substitute:
      APP: *appname
      VOLSYNC_CLAIM: lidarr-config
      VOLSYNC_CAPACITY: 5Gi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: downloads
  timeout: 5m
  wait: false
