---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: forgejo
  labels:
    kubernetes.io/service-name: forgejo
addressType: IPv4
endpoints:
  - addresses:
      - 10.17.1.2
ports:
  - name: http
    appProtocol: http
    protocol: TCP
    port: 3000
