---
# yaml-language-server: $schema=https://k8s-schemas.aresu.eu/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jellyfin-sync
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: jellyfin-sync-secret
    creationPolicy: Owner
  data:
    - secretKey: PLEX_TOKEN
      remoteRef:
        key: Plex
        property: token
    - secretKey: JELLYFIN_TOKEN
      remoteRef:
        key: Jellyfin
        property: api_key
    - secretKey: EMBY_TOKEN
      remoteRef:
        key: Emby
        property: api_key
